"use client";

import { ArrowLeft, Beaker, ClipboardList, FlaskConical, Info, TriangleAlert } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState, type FormEvent } from "react";
import { formatGrams } from "@/components/labs-workspace";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import type { LabFormula } from "@/lib/types";

export function LabFormulaWorkspace({ formula }: { formula: LabFormula }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [batchNumber, setBatchNumber] = useState(""); const [grams, setGrams] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const target = Number(grams);
  const preview = useMemo(() => calculate(formula, target), [formula, target]);
  async function createBatch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); if (!Number.isFinite(target) || target <= 0) { setError("Enter a batch size greater than zero in grams."); return; } if (!batchNumber.trim()) { setError("Enter the batch number."); return; } setSubmitting(true); try { const response = await fetch("/api/labs/batches", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ formulaId: formula.id, batchNumber: batchNumber.trim(), targetGrams: target }) }); const result = await response.json().catch(() => ({})) as { message?: string }; if (!response.ok) { setError(result.message || "Unable to create this batch."); return; } setOpen(false); router.push("/labs"); router.refresh(); } catch { setError("Unable to create this batch. Check your connection and try again."); } finally { setSubmitting(false); } }
  return <section className="workspace workspace--labs"><Link className="labs-back" href="/labs"><ArrowLeft size={16} />Labs</Link><header className="labs-formula-header"><span className="labs-formula-header__mark"><FlaskConical size={28} strokeWidth={1.45} /></span><div><h1>{formula.title}</h1><p>{formula.subtitle}</p></div><div className="labs-formula-header__actions"><Link className="ui-button ui-button--outline ui-button--default-size" href={`/labs/batches?formula=${encodeURIComponent(formula.id)}`}><ClipboardList size={17} />Batches</Link><Button variant="primary" onClick={() => { setError(""); setOpen(true); }}><Beaker size={17} />Create batch</Button></div></header>
    <div className="labs-formula-note"><Info size={17} /><p>{formula.notes}</p></div>
    <section className="labs-recipe" aria-labelledby="formula-ratio-heading"><div className="labs-section-heading"><div><h2 id="formula-ratio-heading">Formula ratio</h2><p>Percentages are weight by weight. Batch calculations use grams.</p></div></div><div className="labs-recipe-table-wrap"><table className="labs-recipe-table"><thead><tr><th>Ingredient</th><th>Phase</th><th>Ratio</th><th>Inventory</th></tr></thead><tbody>{formula.lines.map((line) => <tr key={line.ingredientId}><td><strong>{line.ingredient}</strong>{line.note && <small>{line.note}</small>}</td><td>{line.phase || "—"}</td><td>{line.calculation === "remainder" ? "Remainder to 100%" : line.calculation === "manual" ? "Manual q.s." : `${line.percentage}%`}</td><td>{line.quantityKnown ? formatGrams(line.quantityGrams) : "Not counted"}</td></tr>)}</tbody></table></div></section>
    <Dialog open={open} onOpenChange={(next) => { if (!submitting) setOpen(next); }}><DialogContent className="lab-batch-dialog" aria-describedby="lab-batch-description"><div className="lab-batch-dialog__header"><DialogTitle>Create batch</DialogTitle><DialogDescription id="lab-batch-description">Enter the batch reference and total target weight. You will review every calculated deduction before confirming.</DialogDescription></div><form onSubmit={createBatch}><div className="lab-batch-fields"><label><span>Batch number</span><Input value={batchNumber} onChange={(event) => setBatchNumber(event.target.value)} placeholder="e.g. UES-2026-001" maxLength={80} autoFocus /></label><label><span>Batch size (g)</span><Input value={grams} onChange={(event) => setGrams(event.target.value)} type="number" inputMode="decimal" min="0.001" step="0.001" placeholder="e.g. 4000" /></label></div>{Number.isFinite(target) && target > 0 && <div className="lab-batch-preview"><h3>Review deductions</h3>{preview.map((line) => <div key={line.ingredientId}><span>{line.ingredient}</span><strong>{formatGrams(line.required)}</strong><small>{line.known ? `${formatGrams(line.remaining)} remaining` : "Not counted"}</small></div>)}{formula.lines.some((line) => line.calculation === "manual") && <p><Info size={15} />Manual q.s. pH-adjustment ingredients are shown on the formula but excluded from automated deductions.</p>}</div>}{error && <p className="lab-form-error" role="alert"><TriangleAlert size={16} />{error}</p>}<div className="lab-batch-actions"><Button variant="outline" onClick={() => setOpen(false)} disabled={submitting}>Cancel</Button><Button variant="primary" type="submit" disabled={submitting}>{submitting ? "Creating…" : "Confirm & create batch"}</Button></div></form></DialogContent></Dialog>
  </section>;
}

function calculate(formula: LabFormula, target: number) { const fixed = formula.lines.filter((line) => line.calculation === "fixed").reduce((total, line) => total + (line.percentage ?? 0), 0); return formula.lines.flatMap((line) => { if (line.calculation === "manual") return []; const percentage = line.calculation === "remainder" ? 100 - fixed : line.percentage ?? 0; const required = Math.round(target * percentage * 10) / 1000; return [{ ...line, required, remaining: Math.round((line.quantityGrams - required) * 1000) / 1000, known: line.quantityKnown }]; }); }
