/** Every API route that changes state is classified here for MCP parity review. */
export const MCP_STAFF_ROUTE_COVERAGE = {
  "development/import-legacy": { internalReason: "Development-only legacy importer" },
  "employees/accept-invite": { internalReason: "Invitee's one-time password setup, not an owner staff action" },
  employees: { tools: ["invite_employee"] },
  "inventory/clear-channel-mappings": { internalReason: "Retired HTTP 410 endpoint" },
  "inventory/master": { internalReason: "Retired HTTP 410 endpoint" },
  "inventory/packaging": { tools: ["create_packaging_material", "update_packaging_material", "archive_packaging_material"] },
  "inventory/physical-channel-product-links": { tools: ["set_channel_product_link", "clear_channel_product_link"] },
  "inventory/physical-mappings": { tools: ["set_channel_listing_mapping", "clear_channel_listing_mapping"] },
  "inventory/physical/products/[productId]": { tools: ["rename_physical_product", "add_physical_variant", "archive_physical_product"] },
  "inventory/physical/variants/[variantId]": { tools: ["update_physical_variant", "archive_physical_variant"] },
  "inventory/physical": { tools: ["set_physical_variant_stock", "set_physical_variant_stocks"] },
  "inventory/refresh-tiktok": { tools: ["refresh_tiktok_inventory"] },
  "labs/batches/[batchId]": { tools: ["record_lab_batch_packaging"] },
  "labs/batches/[batchId]/notes": { tools: ["set_lab_batch_notes"] },
  "labs/batches": { tools: ["create_lab_batch"] },
  "labs/formulas/[formulaId]/packaging": { tools: ["set_lab_formula_packaging"] },
  "labs/formulas": { tools: ["create_lab_formula"] },
  "labs/ingredients/import": { tools: ["import_lab_ingredients"] },
  "labs/ingredients": { tools: ["create_lab_ingredient", "update_lab_ingredient", "archive_lab_ingredient"] },
  "mcp/oauth/authorize": { internalReason: "OAuth authorization protocol" },
  "mcp/oauth/register": { internalReason: "OAuth client registration protocol" },
  "mcp/oauth/revoke": { internalReason: "OAuth token revocation protocol" },
  "mcp/oauth/token": { internalReason: "OAuth token exchange protocol" },
  mcp: { internalReason: "MCP protocol transport" },
  "orders/[orderId]/parcel2go": { tools: ["link_parcel2go_shipment"] },
  sync: { tools: ["run_direct_channel_sync"] },
  "tiktok-ads/refresh": { tools: ["refresh_tiktok_ads_report"] },
  "tiktok/webhook": { internalReason: "Verified provider webhook" },
  "webhooks/parcel2go": { internalReason: "Verified provider webhook" },
  "tiktok/authorize": { tools: ["start_tiktok_shop_connection"] },
  "tiktok-ads/authorize": { tools: ["start_tiktok_ads_connection"] },
  // VAT workspace (ADR 0011): staff-only in this phase; MCP VAT tools need their own decision.
  "vat/connections/dropbox": { internalReason: "VAT shared connection management; MCP VAT tools deferred (ADR 0011)" },
  "vat/invoices/[invoiceId]": { internalReason: "VAT invoice review in the staff workspace; MCP VAT tools deferred (ADR 0011)" },
  "vat/invoices/[invoiceId]/remove": { internalReason: "Retained VAT removal in the staff workspace; MCP VAT tools deferred (ADR 0011)" },
  "vat/invoices/[invoiceId]/restore": { internalReason: "VAT restore in the staff workspace; MCP VAT tools deferred (ADR 0011)" },
  "vat/mailboxes/[mailboxId]": { internalReason: "VAT shared connection management; MCP VAT tools deferred (ADR 0011)" },
  "vat/api-keys": { internalReason: "VAT service key management in the staff workspace; never exposed to assistants" },
  "vat/unlock": { internalReason: "VAT workspace password check for the signed-in browser" },
  "vat/runs": { internalReason: "Browser-driven Get invoices run; MCP VAT tools deferred (ADR 0011)" },
  "vat/runs/[runId]/step": { internalReason: "Browser-driven Get invoices run step" },
  "vat/runs/[runId]/resume": { internalReason: "Browser-driven Get invoices run control" },
  "vat/runs/[runId]/cancel": { internalReason: "Browser-driven Get invoices run control" },
  "vat/uploads": { internalReason: "Browser-to-Dropbox upload handshake; not an assistant action" },
  "vat/uploads/[uploadId]/complete": { internalReason: "Browser-to-Dropbox upload handshake; not an assistant action" },
} as const;
